In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
dtset = pd.read_csv("Social_Network_Ads.csv")
dtset.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [3]:
dtset = pd.get_dummies(dtset,drop_first=True)
independant = dtset.drop('User ID', axis=1)
dept = dtset[['User ID']]

In [6]:
dtset

,User ID,Age,EstimatedSalary,Purchased,Gender_Male
0,15624510,19,19000,0,True
1,15810944,35,20000,0,True
2,15668575,26,43000,0,False
3,15603246,27,57000,0,False
4,15804002,19,76000,0,True
...,...,...,...,...,...
395,15691863,46,41000,1,False
396,15706071,51,23000,1,True
397,15654296,50,20000,1,False
398,15755018,36,33000,0,True


In [7]:

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(independant, dept, test_size = 1/3, random_state=0)


In [8]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

C:\Users\ssiva\anaconda3\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [10]:
y_predict = classifier.predict(x_test)
from sklearn.metrics import r2_score
rscore=r2_score(y_test, y_predict)
rscore

-0.836440271748778

In [12]:
y_pred = classifier.predict(x_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)     
cm

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [13]:
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)
print(clf_report)

              precision    recall  f1-score   support

    15566689       0.00      0.00      0.00       1.0
    15570769       0.00      0.00      0.00       1.0
    15570932       0.00      0.00      0.00       1.0
    15571059       0.00      0.00      0.00       0.0
    15574305       0.00      0.00      0.00       0.0
    15575247       0.00      0.00      0.00       0.0
    15577178       0.00      0.00      0.00       1.0
    15577806       0.00      0.00      0.00       0.0
    15578006       0.00      0.00      0.00       1.0
    15578738       0.00      0.00      0.00       0.0
    15579212       0.00      0.00      0.00       1.0
    15581654       0.00      0.00      0.00       1.0
    15582066       0.00      0.00      0.00       0.0
    15582492       0.00      0.00      0.00       0.0
    15583681       0.00      0.00      0.00       1.0
    15584114       0.00      0.00      0.00       0.0
    15584320       0.00      0.00      0.00       1.0
    15584545       0.00    

C:\Users\ssiva\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\ssiva\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\ssiva\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\ssiva\anaconda3\Lib\site-packages\sklea

In [14]:
print(cm)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [21]:
x_train.columns

Index(['Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [22]:
age_input=float(input("Age:"))
salary_input=float(input("Salary:"))
purchaseIP =float(input("0 or 1:"))
sex_male_input=int(input("Sex Male 0 or 1:"))

Age: 32
Salary: 60000
0 or 1: 1
Sex Male 0 or 1: 1


In [23]:
classifier.predict([[age_input,salary_input,purchaseIP, sex_male_input]])
#dir(clf_report)

C:\Users\ssiva\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([15675185])